{{ config( materialized="view") }}

WITH "t1" AS (
  SELECT
    "t0"."tenure" AS "tenure",
    "t0"."senior_citizen" AS "senior_citizen",
    "t0"."monthly_charges" AS "monthly_charges",
    "t0"."total_charges" AS "total_charges",
    CAST(CASE WHEN "t0"."phone_service" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v1",
    CAST(CASE WHEN "t0"."phone_service" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v2",
    CAST(CASE WHEN "t0"."multiple_lines" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v3",
    CAST(CASE WHEN "t0"."multiple_lines" = 'No phone service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v4",
    CAST(CASE WHEN "t0"."multiple_lines" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v5",
    CAST(CASE WHEN "t0"."partner" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v6",
    CAST(CASE WHEN "t0"."partner" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v7",
    CAST(CASE WHEN "t0"."dependents" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v8",
    CAST(CASE WHEN "t0"."dependents" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v9",
    CAST(CASE WHEN "t0"."contract" = 'Month-to-month' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v10",
    CAST(CASE WHEN "t0"."contract" = 'One year' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v11",
    CAST(CASE WHEN "t0"."contract" = 'Two year' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v12",
    CAST(CASE WHEN "t0"."paperless_billing" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v13",
    CAST(CASE WHEN "t0"."paperless_billing" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v14",
    CAST(CASE WHEN "t0"."payment_method" = 'Bank transfer (automatic)' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v15",
    CAST(CASE WHEN "t0"."payment_method" = 'Credit card (automatic)' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v16",
    CAST(CASE WHEN "t0"."payment_method" = 'Electronic check' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v17",
    CAST(CASE WHEN "t0"."payment_method" = 'Mailed check' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v18",
    CAST(CASE WHEN "t0"."internet_service" = 'DSL' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v19",
    CAST(CASE WHEN "t0"."internet_service" = 'Fiber optic' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v20",
    CAST(CASE WHEN "t0"."internet_service" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v21",
    CAST(CASE WHEN "t0"."online_security" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v22",
    CAST(CASE WHEN "t0"."online_security" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v23",
    CAST(CASE WHEN "t0"."online_security" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v24",
    CAST(CASE WHEN "t0"."online_backup" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v25",
    CAST(CASE WHEN "t0"."online_backup" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v26",
    CAST(CASE WHEN "t0"."online_backup" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v27",
    CAST(CASE WHEN "t0"."device_protection" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v28",
    CAST(CASE WHEN "t0"."device_protection" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v29",
    CAST(CASE WHEN "t0"."device_protection" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v30",
    CAST(CASE WHEN "t0"."tech_support" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v31",
    CAST(CASE WHEN "t0"."tech_support" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v32",
    CAST(CASE WHEN "t0"."tech_support" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v33",
    CAST(CASE WHEN "t0"."streaming_tv" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v34",
    CAST(CASE WHEN "t0"."streaming_tv" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v35",
    CAST(CASE WHEN "t0"."streaming_tv" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v36",
    CAST(CASE WHEN "t0"."streaming_movies" = 'No' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v37",
    CAST(CASE WHEN "t0"."streaming_movies" = 'No internet service' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v38",
    CAST(CASE WHEN "t0"."streaming_movies" = 'Yes' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v39",
    CAST(CASE WHEN "t0"."gender" = 'Female' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v40",
    CAST(CASE WHEN "t0"."gender" = 'Male' THEN 1 ELSE 0 END AS DOUBLE) AS "oh_v41",
    "customer_id"
  FROM {{ ref('raw_feat')}} AS "t0"
)
SELECT
  "t1"."oh_v1" AS "oh__phone_service_No",
  "t1"."oh_v2" AS "oh__phone_service_Yes",
  "t1"."oh_v3" AS "oh__multiple_lines_No",
  "t1"."oh_v4" AS "oh__multiple_lines_No_phone_service",
  "t1"."oh_v5" AS "oh__multiple_lines_Yes",
  "t1"."oh_v19" AS "oh__internet_service_DSL",
  "t1"."oh_v20" AS "oh__internet_service_Fiber_optic",
  "t1"."oh_v21" AS "oh__internet_service_No",
  "t1"."oh_v22" AS "oh__online_security_No",
  "t1"."oh_v23" AS "oh__online_security_No_internet_service",
  "t1"."oh_v24" AS "oh__online_security_Yes",
  "t1"."oh_v25" AS "oh__online_backup_No",
  "t1"."oh_v26" AS "oh__online_backup_No_internet_service",
  "t1"."oh_v27" AS "oh__online_backup_Yes",
  "t1"."oh_v28" AS "oh__device_protection_No",
  "t1"."oh_v29" AS "oh__device_protection_No_internet_service",
  "t1"."oh_v30" AS "oh__device_protection_Yes",
  "t1"."oh_v31" AS "oh__tech_support_No",
  "t1"."oh_v32" AS "oh__tech_support_No_internet_service",
  "t1"."oh_v33" AS "oh__tech_support_Yes",
  "t1"."oh_v34" AS "oh__streaming_tv_No",
  "t1"."oh_v35" AS "oh__streaming_tv_No_internet_service",
  "t1"."oh_v36" AS "oh__streaming_tv_Yes",
  "t1"."oh_v37" AS "oh__streaming_movies_No",
  "t1"."oh_v38" AS "oh__streaming_movies_No_internet_service",
  "t1"."oh_v39" AS "oh__streaming_movies_Yes",
  "t1"."oh_v40" AS "oh__gender_Female",
  "t1"."oh_v41" AS "oh__gender_Male",
  "t1"."oh_v6" AS "oh__partner_No",
  "t1"."oh_v7" AS "oh__partner_Yes",
  "t1"."oh_v8" AS "oh__dependents_No",
  "t1"."oh_v9" AS "oh__dependents_Yes",
  "t1"."oh_v10" AS "oh__contract_Month_to_month",
  "t1"."oh_v11" AS "oh__contract_One_year",
  "t1"."oh_v12" AS "oh__contract_Two_year",
  "t1"."oh_v13" AS "oh__paperless_billing_No",
  "t1"."oh_v14" AS "oh__paperless_billing_Yes",
  "t1"."oh_v15" AS "oh__payment_method_Bank_transfer_automatic",
  "t1"."oh_v16" AS "oh__payment_method_Credit_card_automatic",
  "t1"."oh_v17" AS "oh__payment_method_Electronic_check",
  "t1"."oh_v18" AS "oh__payment_method_Mailed_check",
  CAST("t1"."tenure" AS DOUBLE) AS "remainder__tenure",
  CAST("t1"."senior_citizen" AS DOUBLE) AS "remainder__senior_citizen",
  "t1"."monthly_charges" AS "remainder__monthly_charges",
  "t1"."total_charges" AS "remainder__total_charges",
  "customer_id",
  '1.0' AS "model_version"
FROM "t1" AS "t1"