
name: 'dbt_orb_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_orb_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  fake_today: '2025-08-05'
  dbt_vars: ['fake_today']

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_orb_demo:
    +materialized: view

tests:
  +store_failures: true
  +store_failues_as: view
  +schema: "audit"

snapshots:
  dbt_orb_demo:
    pred_churn:
      schema: snapshots
      database: analytics
      unique_key: customer_id
      strategy: check
      check_cols: ['pred']
